### ISSUE TITLE
在不同的计算设备之间迁移部分，不是 MegEngine 的设计初衷

### ISSUE THREAD

**Issue by xxr3376** [MegEngine/Tutorials#1]
MegEngine 的设计是希望用户用 `set_default_device` 全局指定设备（且我们多卡并行是依靠多进程实现，因此几乎不需要涉及到跨设备），而不是依靠 `to` 频繁在设备间拷贝（这会使得模型比较低 & 更不容易在推理侧运行）。因此建议在 Tutorial 部分只提 `set_default_device` 即可，`to` 的使用属于极特殊情况，建议在高阶部分再提及。

**Comment by MegChai** [comment]
已经将有关 `device` 的部分移动到 `example` 文件夹中，https://github.com/MegEngine/Tutorial/commit/185d7d81bfaf0f04890707360f2aabba0bedd7fb

**Comment by MegChai** [comment]
@all-contributors Please add @xxr3376  for review

**Comment by MegChai** [comment]
@allcontributors Hey my cute bot. Please delete/remove @xxr3376 from the contributor list. He wants to keep a low profile.
